# Generated by Django 3.2 on 2022-03-30 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('usd_value', models.DecimalField(blank=True, decimal_places=3, default='0.00', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usd_value'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('usd_spent', models.DecimalField(decimal_places=3, max_digits=10)),
                ('usd_earned', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_investment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('added_to_portfolio', models.DateTimeField(auto_now_add=True)),
                ('pnl', models.DecimalField(decimal_places=3, default='0.00', max_digits=10)),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['added_to_portfolio'],
            },
        ),
    ]
