# Generated by Django 3.2 on 2022-03-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
