# Generated by Django 3.2 on 2022-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_assets_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AveragePrice',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='CurrentInvestment',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='USDEarned',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='USDSpent',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='USDvalue',
            field=models.DecimalField(decimal_places=3, default='0.00', max_digits=10),
        ),
    ]
