# Generated by Django 3.2 on 2022-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220405_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_investment',
        ),
    ]
