# Generated by Django 3.2 on 2022-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_asset_current_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_holdings',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
