# Generated by Django 3.2 on 2022-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_asset_current_holdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_holdings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
