# Generated by Django 3.2 on 2022-03-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220316_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-usd_value']},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='AveragePrice',
            new_name='average_price',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='CurrentInvestment',
            new_name='current_investment',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='PnL',
            new_name='pnl',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='USDEarned',
            new_name='usd_earned',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='USDSpent',
            new_name='usd_spent',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='USDvalue',
            new_name='usd_value',
        ),
    ]
