# Generated by Django 3.2 on 2022-04-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_asset_current_holdings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-current_holdings']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='usd_value',
        ),
    ]
