# Generated by Django 3.2 on 2022-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220420_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
