# Generated by Django 3.2 on 2022-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220420_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
