# Generated by Django 3.2 on 2022-04-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_asset_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-ticker']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_holdings',
        ),
    ]
