# Generated by Django 3.2 on 2022-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
